### PR TITLE
Improve site style

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Here's a little style "improvement". Try it and say if like it or not. Waiting for your review!

### CODE REVIEW

**Comment by gkoz** [comment]
A less contrasty background (like you suggest) might indeed be good. The white padding around `page-content` though, it adds noise while there already is clear separation between e.g. header and the content. (The padding is needed but looks like it has to be the same color).

I'd change the first sentence to `h2` (`##`) to make it less jarring.

A different background for announcements is a very good idea but the color seems out of place :( ~~Maybe something yellowish could work there. The badges have a warm color after all.~~ Or better yet make it match the code blocks below?

Do you think we might put more text under the badges so there wouldn't be so much blank space?

**Comment by gkoz** [comment]
Also the screenshot is way too big now haha

**Comment by GuillaumeGomez** [comment]
> The white padding around page-content though, it adds noise while there already is clear separation between e.g. header and the content. (The padding is needed but looks like it has to be the same color).

I don't have white padding. So I'm not sure to see what's you're talking about.

> I'd change the first sentence to h2 (##) to make it less jarring.

Changing the first sentence to h2 would make to slow from my point of view.

> A different background for announcements is a very good idea but the color seems out of place :( Maybe something yellowish could work there. The badges have a warm color after all. Or better yet make it match the code blocks below?

The goal of the different news background color is to attract reader attention. I made it less flashy, you'll say if you prefer.

> Do you think we might put more text under the badges so there wouldn't be so much blank space?

Definitely but I didn't have idea. If you have any, please try it out ! :)

**Comment by gkoz** [comment]
Here's a screenshot with some notes:
[](http://i.imgur.com/IhwjxaG.png)

Yellow might work if we make it like a post-it note I guess. It looks a bit greyish-dirty now ;) Blue links might not look good on yellow :(

**Comment by GuillaumeGomez** [comment]
Okay, I see your points ! I'm gonna work on it then.

**Comment by GuillaumeGomez** [comment]
And like this ?

**Comment by gkoz** [comment]
I feel that `<h1>` and `<center>` just don't work in this context. They require simple structure: either a wall of text underneath, or a lot of space around, consider http://getbootstrap.com -- it has a logo, a sentence and a button above the fold, that's all. If we're to have many elements -- the badges, a screenshot (it needs to find its place as well BTW), a bit of text, and announcements, they need a more tight organization. I know it's difficult to do. http://rust-lang.org is a good example and their description is not too big.

So you have the presentation text flow around the announcements. It seems we can put announcements, badges and screenshot together there (modulo the padding issues):
[](http://i.imgur.com/7iRX55z.png)

**Comment by gkoz** [comment]
That big chunk of Rust code might not be a good fit for the front page...

**Comment by GuillaumeGomez** [comment]
I put out the crate badges. I still think we should keep the "Annoucements" div in here (with just one element in it, it's very nice). For the rest, I'm too tired for the moment.

**Comment by gkoz** [comment]
Here's my take at applying the background suggestions but also scaling back the complexity (no wide layout, no columns): https://github.com/gkoz/gkoz.github.io/tree/float-right

**Comment by GuillaumeGomez** [comment]
Sorry, I was a bit busy. I'm taking a look !

**Comment by GuillaumeGomez** [comment]
Ok, so what about this version ?

**Comment by gkoz** [comment]
This could work. You'll want to rebase onto master to take advantage of badges being moved to `_include`.
The padding problem ("I see <body> through this padding" on the first screenshot) is still here.

Also since only the `wide-wrapper` has the `#F7F7F7` background, all the other pages are still white. I don't think that's the intention?

**Comment by GuillaumeGomez** [comment]
> This could work. You'll want to rebase onto master to take advantage of badges being moved to `_include`.

I'm going to rebase then.

> The padding problem ("I see through this padding" on the first screenshot) is still here.

I like having the body detached from the header and the footer.

> Also since only the wide-wrapper has the #F7F7F7 background, all the other pages are still white. I don't think that's the intention?

I didn't take a look to the other pages yet. Since the main one is nearly good now, I will !

**Comment by gkoz** [comment]
> I like having the body detached from the header and the footer.

How about smaller values, up to `10px`? I feel the white bar draws too much attention otherwise.

**Comment by GuillaumeGomez** [comment]
Yes sure.

**Comment by gkoz** [comment]
Oh. Looks like I didn't actually push the commit which moved the badges code :/

**Comment by GuillaumeGomez** [comment]
It explains why I didn't see any change. :p

**Comment by gkoz** [comment]
Now it's there

**Comment by GuillaumeGomez** [comment]
I rebased.

**Comment by gkoz** [comment]
Looks good!

**Comment by gkoz** [comment]
Do you think you might squash some of the commits?

**Comment by GuillaumeGomez** [comment]
If this version is okay with you then yes.

**Comment by GuillaumeGomez** [comment]
Squashed !

**Comment by gkoz** [comment]
Cool! Thanks for taking part in this tedious work. ;) I'll tweak the wording a bit more and then we'll be ready for the switch.

**Comment by GuillaumeGomez** [comment]
I'm directly concerned by this so it's normal for me to contribute. I can't wait to see this online ! :D

**Pull request merged**
